server:
  port: ${port:9091} # 不传-Dport=**默认9091
spring:
  application:
    name: user-service
#  datasource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url=jdbc:mysql://203.195.237.107:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 123456
#    防止数据库连接释放完
#    test-on-borrow: true
#    validation-query: SELECT 1
#  jpa
#    database: mysql
#    show-sql: true
#    hibernate
#      ddl-auto: update
#    generate-ddl: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
test:
  name: zm
